# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py38

[flake8]
ignore = E501,C901
max-line-length = 1000
exclude = tests/*
max-complexity = 10

[testenv]
deps =
    pytest
    emoji
    python-telegram-bot
    apscheduler
commands =
    pytest -s -W ignore::DeprecationWarning
